module-name: telemetry
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:main
  - europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:3.0.7-1e5449d3
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20240404-fd3588ce
  - europe-docker.pkg.dev/kyma-project/prod/tpi/telemetry-self-monitor:2.53.0-8691013b
  - europe-docker.pkg.dev/kyma-project/prod/kyma-otel-collector:0.102.1-0.1.16
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
