name: PR Github Checks

on:
  #  pull_request_target:
  pull_request:
    branches:
      - "main"
      - "release-*"
    types:
      - opened
      - reopened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  pr-label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for area label
        if: always()
        run: |
          gh pr list --json number,title,labels --state open --limit 1 | \
          jq '.[] | select(.number == ${{ github.event.pull_request.number }}) | .labels[].name' | \
          grep -q '^area/' || exit 1

      - name: Check for kind label
        if: always()
        run: |
          gh pr list --json number,title,labels --state open --limit 1 | \
          jq '.[] | select(.number == ${{ github.event.pull_request.number }}) | .labels[].name' | \
          grep -q '^kind/' || exit 1

      - name: Check if kind label matches pr title prefix
        if: always()
        run: |
          kind_label=$(gh pr list --json number,title,labels --state open --limit 1 | \
          jq '.[] | select(.number == ${{ github.event.pull_request.number }}) | .labels[].name' | \
          grep '^kind/')
          kind_label_to_pr_title_prefix='{"kind/bug":"fix","kind/feature":"feat","kind/docs":"docs","kind/chore":"chore","kind/test":"test","kind/deps":"deps"}'
          prefix=$(echo $kind_label_to_pr_title_prefix | jq -r ".$kind_label")
          if [[ ! ${{ github.event.pull_request.title }} =~ ^$prefix ]]; then
            echo "PR title should start with $prefix"
            exit 1
          fi
        

  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate title
        uses: amannn/action-semantic-pull-request@47b15d52c5c30e94a17ec87eb8dd51ff5221fed9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            deps
            chore
            docs
            feat
            fix
            test
          requireScope: false
          subjectPattern: ^([A-Z].*[^.]|bump .*)$
