name: Tag Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # wait for the build to succeed so that the manager image is available
      - name: Wait for the 'post-telemetry-manager-build-release' job to succeed
        uses: kyma-project/wait-for-commit-status-action@b805fd5b536679183dc540369522d4d38811c182
        with:
          context: "post-telemetry-manager-build-release"
          commit_ref: "${{ github.ref_name }}" # 'github.ref_name' is the release tag which triggered the Github action
          timeout: 600000 # 10 minutes in milliseconds
          # The check interval is kept long otherwise it will exhaust the GitHub rate limit (More info: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting)
          check_interval: 60000 # 1 minute in milliseconds
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_OWNER: "${{ github.repository_owner }}"
          GITHUB_REPO: "telemetry-manager"

      - name: Install tools
        shell: bash
        run: make install-tools

      - name: Release
        run: hack/release.sh ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_CURRENT_TAG: "${{ github.ref_name }}" # Explicitly set release tag to do not use -dev tag
